### ISSUE TITLE
Error: Cannot find module 'chalk'

### ISSUE THREAD

**Issue by nwaughachukwuma** [vuejs-templates/pwa#152]
Hey guys (@jeffposnick and all) am getting this error on my Heroku App after CI/CD from GitLab to Heroku. Following is the gitlab-ci.yml script:

```
image: node:6

stages:
  - ver
  - init
  - tests
  - deploy

cache:
  paths:
    - node_modules/

ver:
  stage: ver
  script:
    - node --version
    - whoami
init:
  stage: init
  script:
    - npm install -g chalk
    - npm cache clean
    - rm -rf node-modules
    - npm install
    
run_tests:
 # needed for testing selenium on docker with java
  image: karthikiyengar/node-nightwatch:0.0.1
  stage: tests
  script:
    - sudo npm install
    - sudo npm test

deploy_staging:
  stage: deploy
  script:
    - npm install -g chalk
    - npm cache clean
    - rm -rf node-modules
    - npm install    
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/webapp-staging.git
    - git push heroku master
    - echo "Deployed to staging server"
  environment: staging
  only:
    - master

deploy_production:
  stage: deploy
  script:
    - npm install -g chalk
    - npm cache clean
    - rm -rf node-modules
    - npm install
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/webapp.git
    - git push heroku master
    - echo "Deployed to production server"
  environment: production
  when: manual
  only:
    - master
```
Help will be greatly appreciated. Thanks
